name: 'git-restore-mtime'
description: "Restore file's modified time (timestamp) based on git commits"
author: 'Pixelcop Research, Inc.'
branding:
  icon: 'clock'
  color: 'orange'
runs:
  using: 'node12'
  main: 'dist/index.js'
